BUILD SUCCESSFUL Total time: 2 seconds -- listing properties -- mail.smtp.gmail=smtp.gmail.com mail.smtps.quitwait=true mail.smtp.username=hawat.thufir@gmail.com mail.smtp.starttls.enable=true mail.smtp.connectiontimeout=2000 mail.smtp.user=hawat.thufir mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory mail.smtp.password=password nntp.host=nntp://localhost/ mail.smtp.socketFactory.port=465 mail.smtp.timeout=2000 mail.imap.port=993 mail.imap.timeout=5000 mail.smtp.port=587 mail.smtp.auth=true mail.imap.host=imap.gmail.com mail.nntp.newsrc.file=/home/thufir/.newsrc mail.imap.connectiontimeout=5000 mail.smtp.host=smtp.gmail.com
========message follows==========

Exception in thread "main" java.lang.RuntimeException: javax.mail.SendFailedException: Send failed;
  nested exception is:
	javax.mail.SendFailedException: 5.5.1 http://support.google.com/mail/bin/answer.py?answer=14257 ef10sm55111315pac.1 - gsmtp
	at net.bounceme.dur.nntp.SendTLS.sendMessage(SendTLS.java:61)
	at net.bounceme.dur.nntp.SendTLS.<init>(SendTLS.java:23)
	at net.bounceme.dur.nntp.SendTLS.main(SendTLS.java:34)
Caused by: javax.mail.SendFailedException: Send failed;
  nested exception is:
	javax.mail.SendFailedException: 5.5.1 http://support.google.com/mail/bin/answer.py?answer=14257 ef10sm55111315pac.1 - gsmtp
	at javax.mail.Transport.doSend(Transport.java:231)
	at javax.mail.Transport.send(Transport.java:75)
	at net.bounceme.dur.nntp.SendTLS.sendMessage(SendTLS.java:57)
	... 2 more
thufir@dur:~/NetBeansProjects/MailFromNNTP$