BUILD SUCCESSFUL Total time: 2 seconds -- listing properties -- mail.smtp.starttls.enable=true mail.smtp.port=587 mail.imap.host=imap.gmail.com mail.smtp.auth=true mail.smtp.username=hawat.thufir@gmail.com mail.smtp.password=password
========message follows==========

Exception in thread "main" java.lang.RuntimeException: javax.mail.SendFailedException: Send failed;
  nested exception is:
	javax.mail.MessagingException: Connection refused;
  nested exception is:
	java.net.ConnectException: Connection refused
	at net.bounceme.dur.nntp.SendTLS.sendMessage(SendTLS.java:59)
	at net.bounceme.dur.nntp.SendTLS.<init>(SendTLS.java:23)
	at net.bounceme.dur.nntp.SendTLS.main(SendTLS.java:34)
Caused by: javax.mail.SendFailedException: Send failed;
  nested exception is:
	javax.mail.MessagingException: Connection refused;
  nested exception is:
	java.net.ConnectException: Connection refused
	at javax.mail.Transport.doSend(Transport.java:231)
	at javax.mail.Transport.send(Transport.java:75)
	at net.bounceme.dur.nntp.SendTLS.sendMessage(SendTLS.java:55)
	... 2 more
thufir@dur:~/NetBeansProjects/MailFromNNTP$